// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppvpakkqegbnfwmdnzgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdnBha2txZWdibmZ3bWRuemdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MDE5NTcsImV4cCI6MjA1MDA3Nzk1N30.BD947WUU6FWFKl-sAryeYfS8jCWP8V_cveXibyNN2bQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);